### ISSUE TITLE
Errors trying to compile firmware

### ISSUE THREAD

**Issue by barrettj** [irkit/device#9]
When trying to compile the firmware via the instructions in the readme I get the following:

```
Arduino: 1.6.1 (Mac OS X), Board: "Arduino Leonardo"

from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:779:31: note: in expansion of macro 'P'
                  strncmp(buf, P("Serial2WiFi APP"), 15) == 0) {
                               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from GSwifi.cpp:35:0:
GSwifi.cpp: In member function 'void GSwifi::parseCmdResponse(char*)':
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
log.h:45:43: note: in definition of macro 'GSLOG_PRINT'
 # define GSLOG_PRINT(a)      Serial.print(a)
                                           ^
GSwifi.cpp:795:17: note: in expansion of macro 'P'
     GSLOG_PRINT(P("c< ")); GSLOG_PRINTLN(buf);
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:809:26: note: in expansion of macro 'P'
         if (strncmp(buf, P("CONNECT "), 8) == 0 && buf[9] == 0) {
                          ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:832:52: note: in expansion of macro 'P'
         if (gs_response_lines_ == 0 && strstr(buf, P("SubNet"))) {
                                                    ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:840:26: note: in expansion of macro 'P'
         if (strncmp(buf, P("IP:"), 3) == 0) {
                          ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from GSwifi.cpp:35:0:
GSwifi.cpp: In member function 'void GSwifi::command(const char*, GSwifi::GSCOMMANDMODE, uint8_t)':
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
log.h:45:43: note: in definition of macro 'GSLOG_PRINT'
 # define GSLOG_PRINT(a)      Serial.print(a)
                                           ^
GSwifi.cpp:903:17: note: in expansion of macro 'P'
     GSLOG_PRINT(P("c> "));
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from GSwifi.cpp:35:0:
GSwifi.cpp: In member function 'void GSwifi::escape(const char*, uint8_t)':
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
log.h:45:43: note: in definition of macro 'GSLOG_PRINT'
 # define GSLOG_PRINT(a)      Serial.print(a)
                                           ^
GSwifi.cpp:920:17: note: in expansion of macro 'P'
     GSLOG_PRINT(P("e> "));
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'int8_t GSwifi::join(GSSECURITY, const char*, const char*, int, char*)':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:996:13: note: in expansion of macro 'PB'
     command(PB("AT+WM=0",1), GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:999:11: note: in expansion of macro 'PB'
     cmd = PB("AT+NDHCP=1,%",1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1007:17: note: in expansion of macro 'PB'
         command(PB("AT+WSEC=0",1), GSCOMMANDMODE_NORMAL);
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1009:15: note: in expansion of macro 'PB'
         cmd = PB("AT+WAUTH=%",1);
               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1014:19: note: in expansion of macro 'PB'
             cmd = PB("AT+WWEP1=%",1);
                   ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1018:15: note: in expansion of macro 'PB'
         cmd = PB("AT+WA=%",1);
               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1029:17: note: in expansion of macro 'PB'
         command(PB("AT+WAUTH=0",1), GSCOMMANDMODE_NORMAL);
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1031:15: note: in expansion of macro 'PB'
         cmd = PB("AT+WWPA=%",1);
               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1035:15: note: in expansion of macro 'PB'
         cmd = PB("AT+WA=%",1);
               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1040:17: note: in expansion of macro 'PB'
         command(PB("AT+WAUTH=0",1), GSCOMMANDMODE_NORMAL);
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1042:15: note: in expansion of macro 'PB'
         cmd = PB("AT+WPAPSK=%,%",1);
               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1053:15: note: in expansion of macro 'PB'
         cmd = PB("AT+WA=%",1);
               ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'int GSwifi::listen()':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1077:13: note: in expansion of macro 'PB'
     command(PB("AT+NSTCP=80",1), GSCOMMANDMODE_CONNECT);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'int8_t GSwifi::startLimitedAP()':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1093:13: note: in expansion of macro 'PB'
     command(PB("AT+NSET=192.168.1.1,255.255.255.0,192.168.1.1",1), GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1096:11: note: in expansion of macro 'PB'
     cmd = PB("AT+WPAPSK=IRKitXXXX,XXXXXXXXXX",1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1102:13: note: in expansion of macro 'PB'
     command(PB("AT+WSEC=8",1),           GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1103:13: note: in expansion of macro 'PB'
     command(PB("AT+WAUTH=0",1),          GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1106:13: note: in expansion of macro 'PB'
     command(PB("AT+WM=2",1),             GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1108:13: note: in expansion of macro 'PB'
     command(PB("AT+DHCPSRVR=1",1),       GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1111:11: note: in expansion of macro 'PB'
     cmd = PB("AT+WA=%",1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'int GSwifi::disconnect()':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1128:13: note: in expansion of macro 'PB'
     command(PB("AT+NCLOSEALL",1),  GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1129:13: note: in expansion of macro 'PB'
     command(PB("AT+WD",1),         GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1130:13: note: in expansion of macro 'PB'
     command(PB("AT+DHCPSRVR=0",1), GSCOMMANDMODE_NORMAL);
             ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'int8_t GSwifi::setRegDomain(char)':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1183:17: note: in expansion of macro 'PB'
     char *cmd = PB("AT+WREGDOMAIN=%",1);
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'int8_t GSwifi::request(GSwifi::GSMETHOD, const char*, const char*, uint16_t, GSwifi::GSResponseHandler, uint8_t, uint8_t)':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1198:11: note: in expansion of macro 'PB'
     cmd = PB("AT+DNSLOOKUP=" DOMAIN,1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1214:11: note: in expansion of macro 'PB'
     cmd = PB("AT+NCTCP=",1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1240:11: note: in expansion of macro 'PB'
     cmd = PB("AT+SSLOPEN=%,cacert",1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1278:11: note: in expansion of macro 'PB'
     cmd = PB("S0",1);
           ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:1283:24: note: in expansion of macro 'P'
         serial_->print(P("POST "));
                        ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:1286:24: note: in expansion of macro 'P'
         serial_->print(P("GET "));
                        ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:1289:20: note: in expansion of macro 'P'
     serial_->print(P(" HTTP/1.1\r\nUser-Agent: IRKit/"));
                    ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
pgmStrToRAM.h:22:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define P(s)       pgmStrToRAM(PSTR(s),0)
                                ^
GSwifi.cpp:1295:24: note: in expansion of macro 'P'
         serial_->print(P("Content-Length: "));
                        ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from GSwifi.cpp:25:
GSwifi.cpp: In member function 'char* GSwifi::hostname()':
pgmStrToRAM.h:23:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 #define PB(s,i)    pgmStrToRAM(PSTR(s),i)
                                ^
GSwifi.cpp:1334:17: note: in expansion of macro 'PB'
     char *ret = PB("IRKit%%%%", 0);
                 ^
In file included from GSwifi.cpp:26:0:
pgmStrToRAM.h:29:7: error:   initializing argument 1 of 'char* pgmStrToRAM(char*, uint8_t)' [-fpermissive]
 char *pgmStrToRAM(PROGMEM char *theString, uint8_t index);
       ^
Error compiling.
\
```

**Comment by barrettj** [comment]
It seems to work if I use version 1.0.6 which is available under the "old releases" section, but not if I use 1.6.0 which is the one on the page linked in the readme.

**Comment by mash** [comment]
It seems the compiler option changed in Arduino1.6.1, I'll try to fix this.

**Comment by suisho** [comment]
I got same issue

**Comment by mash** [comment]
Latest push compiles fine on Arduino 1.6.3.
1.6.3's gcc generates code which uses less ROM but a little bit more RAM than 1.0.5 did.
I recommend 1.0.5 if you're just updating to the newest firmware.

```
% /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-size -A 1.0.5/firmware.elf
1.0.5/firmware.elf  :
section             size      addr
.data                872   8388864
.text              27578         0
.bss                1366   8389736

% /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-size -A 1.6.3/firmware.elf
1.6.3/firmware.elf  :
section            size      addr
.data               876   8388864
.text             26194         0
.bss               1364   8389740
```
